### ISSUE TITLE
Bug Report: NO tasks

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/MyScheduledTasks#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened or didn't happen

In my windows 11 and windows server are no task visible when starting the application.
Wen running taskplanner from windows , it shows lots of tasks.

### Version

latest

### Windows Version

(all updates) Microsoft Windows 10.0.22621

### Relevant log output

-

### Anything else?

-

**Comment by Timthreetwelve** [comment]
@CMTriX I'm sorry that you're having a problem with the app, but it is good to hear from you again.

To figure out what's happening, or not happening, would you please 1) click on the three-dot menu in the upper right and select the View Log item, then copy the log and paste it into this issue.  And 2} click on the three-dot menu again. This time select the Open the Tasks File item, copy the JSON file, and paste it into this issue. Alternatively, you could attach the two files to this issue. 

Thanks, 
Tim

**Comment by CMTriX** [comment]
Hello Tim, here is the log file for **Windows 11 Computer 23H2 latest:**
_2024/08/10 07:43:56 INFO   MyScheduledTasks (My Scheduled Tasks) 0.6.1.0 is starting up
2024/08/10 07:43:56 INFO   MyScheduledTasks © 2020-2024 Tim Kennedy
2024/08/10 07:43:56 DEBUG  MyScheduledTasks was started from C:\Users\user\AppData\Local\Programs\T_K\My Scheduled Tasks\MyScheduledTasks.exe
2024/08/10 07:43:56 DEBUG  MyScheduledTasks Build date: maandag 17 juni 2024 21:31  (UTC)
2024/08/10 07:43:56 DEBUG  MyScheduledTasks Commit ID: ed2526f
2024/08/10 07:43:56 DEBUG  MyScheduledTasks is running as Administrator
2024/08/10 07:43:56 DEBUG  Operating System version: Microsoft Windows 10.0.22631
2024/08/10 07:43:56 DEBUG  .NET version:  8.0.7
2024/08/10 07:43:56 DEBUG  Startup culture: nl-NL  UI: nl-NL
2024/08/10 07:43:56 DEBUG  Current culture: en-US  UI: en-US
2024/08/10 07:43:56 DEBUG  290 strings loaded from Languages/Strings.en-US.xaml
2024/08/10 07:43:56 INFO   Read 0 items from C:\Users\user\AppData\Local\Programs\T_K\My Scheduled Tasks\MyTasks.json 
2024/08/10 07:43:57 DEBUG  GetAllTasks found 246/25 tasks and took 0.288602 seconds.`_

**Contents of the taks file json:**
[]

**Comment by CMTriX** [comment]
**log file for Windows Server 2016 all updates**
_2024/08/10 07:49:57 INFO   MyScheduledTasks (My Scheduled Tasks) 0.6.1.0 is starting up
2024/08/10 07:49:57 INFO   MyScheduledTasks © 2020-2024 Tim Kennedy
2024/08/10 07:49:57 DEBUG  MyScheduledTasks was started from C:\Users\Administrator\AppData\Local\Programs\T_K\My Scheduled Tasks\MyScheduledTasks.exe
2024/08/10 07:49:57 DEBUG  MyScheduledTasks Build date: maandag 17 juni 2024 21:31  (UTC)
2024/08/10 07:49:57 DEBUG  MyScheduledTasks Commit ID: ed2526f
2024/08/10 07:49:57 DEBUG  MyScheduledTasks is running as Administrator
2024/08/10 07:49:57 DEBUG  Operating System version: Microsoft Windows 10.0.20348
2024/08/10 07:49:57 DEBUG  .NET version:  8.0.5
2024/08/10 07:49:57 DEBUG  Startup culture: nl-NL  UI: nl-NL
2024/08/10 07:49:57 DEBUG  Current culture: en-US  UI: en-US
2024/08/10 07:49:57 DEBUG  290 strings loaded from Languages/Strings.en-US.xaml
2024/08/10 07:49:57 INFO   Read 0 items from C:\Users\Administrator\AppData\Local\Programs\T_K\My Scheduled Tasks\MyTasks.json 
2024/08/10 07:49:58 DEBUG  GetAllTasks found 160/8 tasks and took 0.6050745 seconds._

**Contents of the taks file json:**
[]

**Comment by Timthreetwelve** [comment]
@CMTriX, it looks like you need to add some tasks. Don't be confused, adding tasks doesn't create new tasks, it just adds existing tasks to the list of tasks that you want to keep track of.

For example, if I wanted to keep track of VSIX Auto Update, `1.` Click on Add Tasks.` 2.` Select the entry. `3.` Click Add Tasks.

![MyScheduledTasks_2024-08-10_20-56-55](https://github.com/user-attachments/assets/df5c2553-a267-4ec8-8607-75d8eac16946)

Go back to the View Tasks page to see that the VSIX update task has been added.

![MyScheduledTasks_2024-08-10_21-00-07](https://github.com/user-attachments/assets/285bfb13-6143-4b71-88c4-21bbf9d4644c)

When selecting tasks from the Add Tasks page you can select multiple tasks and add them all at the same time by using CTRL-click or Shift-click. 

![MyScheduledTasks_2024-08-10_21-10-30](https://github.com/user-attachments/assets/b67c41d6-8bb4-4e85-8d5b-bb643e697065)


I hope this helps.

Tim

**Comment by CMTriX** [comment]
I thought the tool is like a replacement for the windows taskplanner showing all active task. But now i understand that i have to select some task first to watch. Never mind my report. Thanks for your answer/support./tool(s).
